# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='tabel_Id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
