# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_table_registered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='tabel_Id',
            new_name='table_id',
        ),
    ]
