# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20171104_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
    ]
