# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_table_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='checkout',
        ),
    ]
