# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_table_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='cust_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
