# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_table_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='cust_id',
            field=models.IntegerField(),
        ),
    ]
