# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_remove_section_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='imgPath',
            field=models.CharField(max_length=10),
        ),
    ]
