# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_auto_20171107_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='imgPath',
            field=models.CharField(max_length=30),
        ),
    ]
