# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_auto_20171107_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='img',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
