# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_auto_20171107_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='section_id',
            new_name='section',
        ),
    ]
