# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20171106_0716'),
        ('customer', '0003_auto_20171106_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('total', models.FloatField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Item')),
                ('table_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Table')),
            ],
        ),
    ]
