# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20171106_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(default='mo:mo', max_length=30),
            preserve_default=False,
        ),
    ]
