# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20171106_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='table_id',
            new_name='table',
        ),
    ]
