# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20171108_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='table',
            field=models.IntegerField(default=0),
        ),
    ]
