# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_waiter', models.BooleanField(default=False)),
            ],
        ),
    ]
